# Install the pre-commit hooks below with
# 'pre-commit install'

# Auto-update the version of the hooks with
# 'pre-commit autoupdate'

# Run the hooks on all files with
# 'pre-commit run --all'


default_language_version:
  python: python3

repos:
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.13
    hooks:
      - id: insert-license
        args:
          - --license-filepath
          - FILE_HEADER
          - --comment-style
          - "#"
        types: [python]