site_name: Fluid Documentation

theme:
  name: material

plugins:
  - search
  - include-markdown

extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/vdutor
    - icon: fontawesome/brands/github 
      link: https://github.com/vdutor/fluid
  
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 